- hosts: all
  sudo: true
  tasks:
    - name: Install git package
      apt: pkg=git state=present update_cache=yes

    - name: Repository for nodejs
      shell: curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

    - name: Install nodejs and npm
      shell: sudo apt-get install -y nodejs

    - name: Install package build-essential for nodejs
      shell: sudo apt-get install -y build-essential
    
    - name: Install packages from package.json
      npm: path=/home/vagrant/webclient

    - name: Go to webclient folder
      shell: echo "cd ./webclient" >> .bash_profile

    - name: Create environment variables for http-server in package.json
      shell: sh ./webclient/scripts/set_vagrant_env_vars.sh
